#!/usr/bin/env python3
"""
Pull secrets from AWS Systems Manager Parameter Store and write docker-compose env file.

Expected parameter names (SecureString recommended), e.g.:
  /strategos/prod/ANTHROPIC_API_KEY
  /strategos/prod/TELEGRAM_API_HASH
The last path segment becomes the environment variable name.

Requires: AWS CLI credentials (EC2 instance role recommended) and boto3 OR aws CLI in PATH.
Uses subprocess to `aws` CLI so boto3 is not required on minimal AMIs.

Usage:
  export AWS_REGION=us-east-1
  export STRATEGOS_SSM_PREFIX=/strategos/prod/
  python3 scripts/ec2-pull-ssm-env.py --output .env.ssm

Afterwards: docker compose -f docker-compose.prod.yml up -d api worker beat
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys


def _shell_quote(s: str) -> str:
    if not s:
        return '""'
    if "\n" in s or "\r" in s:
        raise ValueError("SSM values must be single-line for .env format")
    if any(c in s for c in ' "\'\\$`!'):
        return "'" + s.replace("'", "'\"'\"'") + "'"
    return s


def fetch_parameters(prefix: str, region: str) -> list[tuple[str, str]]:
    prefix = prefix.rstrip("/") + "/"
    cmd = [
        "aws",
        "ssm",
        "get-parameters-by-path",
        "--path",
        prefix,
        "--recursive",
        "--with-decryption",
        "--region",
        region,
        "--output",
        "json",
    ]
    try:
        raw = subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
    except subprocess.CalledProcessError as e:
        print(e.output or str(e), file=sys.stderr)
        sys.exit(1)
    data = json.loads(raw)
    params = data.get("Parameters") or []
    out: list[tuple[str, str]] = []
    for p in params:
        name = p.get("Name") or ""
        val = p.get("Value")
        if val is None:
            continue
        key = name.rstrip("/").split("/")[-1]
        if not key or key.startswith("."):
            continue
        out.append((key, val))
    return sorted(out, key=lambda x: x[0])


def main() -> None:
    parser = argparse.ArgumentParser(description="Write .env.ssm from SSM Parameter Store")
    parser.add_argument(
        "--output",
        "-o",
        default=".env.ssm",
        help="Output file (default: .env.ssm in cwd)",
    )
    parser.add_argument(
        "--prefix",
        default=os.environ.get("STRATEGOS_SSM_PREFIX", "/strategos/prod/"),
        help="SSM path prefix (default: env STRATEGOS_SSM_PREFIX or /strategos/prod/)",
    )
    parser.add_argument(
        "--region",
        default=os.environ.get("AWS_REGION", os.environ.get("AWS_DEFAULT_REGION", "us-east-1")),
        help="AWS region",
    )
    args = parser.parse_args()

    pairs = fetch_parameters(args.prefix, args.region)
    lines = [
        "# Generated by scripts/ec2-pull-ssm-env.py — do not commit",
        f"# Prefix={args.prefix} region={args.region}",
        "",
    ]
    for k, v in pairs:
        lines.append(f"{k}={_shell_quote(v)}")
    lines.append("")

    out_path = os.path.abspath(args.output)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    try:
        os.chmod(out_path, 0o600)
    except OSError:
        pass
    print(f"Wrote {len(pairs)} variables to {out_path}")


if __name__ == "__main__":
    main()
